"use client";
import {useState} from "react";
import {ArrowUpRight, ArrowRight, Menu} from "lucide-react";
import { SocialLinks } from "@/components/social-links";
import {Brand} from "@/components/site-brand";
import {InquiryDialog} from "@/components/inquiry-dialog";
import {Sheet, SheetContent, SheetTitle, SheetDescription} from "@/components/ui/sheet";
const links=[["Our expertise","/#expertise"],["In practice","/in-practice/crm"],["Events","/events"],["Our firm","/our-firm"]];
export default function EventsPage(){
 const [menuOpen,setMenuOpen]=useState(false);
 const [contactOpen,setContactOpen]=useState(false);
 const [interest,setInterest]=useState("Founder events");
 const [requestId,setRequestId]=useState("");
 function contact(topic="Founder events"){if(topic!=="Founder events"&&topic!=="Venue programming"){window.location.assign("/start?source=event");return;}setMenuOpen(false);setInterest(topic);setRequestId(crypto.randomUUID());setContactOpen(true)}
 return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/>
 <header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,url])=><a key={url} href={url} aria-current={url==="/events"?"page":undefined}>{label}</a>)}</nav><button className="header-contact" onClick={()=>contact("Not sure yet")}>Start a conversation <ArrowUpRight size={17}/></button><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><Menu size={25}/></button></div></header>
 <main id="main">
 <section className="events-hero" aria-labelledby="events-heading"><div className="container events-hero-grid"><div className="events-hero-copy"><a href="/" className="events-breadcrumb">Brown & Gaines <span>/</span> Ryan Brown & Company</a><p className="eyebrow">A Ryan Brown & Company experience</p><h1 id="events-heading">Good things<br/>happen in<br/><em>the right room.</em></h1><p className="events-intro">Curated gatherings, recurring formats, and venue programs designed to give people a reason to enter the room—and come back.</p><a href="#upcoming" className="text-link light-link">Explore upcoming events <ArrowRight size={19}/></a></div><figure className="events-image"><img src="/images/ryan-brown-company-events.jpg" width="1536" height="1024" alt="Guests arriving and connecting inside a restored Detroit event space" fetchPriority="high"/><figcaption className="photo-note">Arrival, energy, connection · Concept imagery</figcaption></figure></div></section>
 <section className="container events-calendar" id="upcoming" aria-labelledby="upcoming-heading"><div className="events-section-heading"><p className="eyebrow">On the calendar</p><h2 id="upcoming-heading">Upcoming events</h2></div><div className="events-coming-soon"><p>Coming soon.</p></div></section>
 <section className="container events-formats" aria-labelledby="formats-heading"><div className="events-section-heading"><p className="eyebrow">Ways we gather</p><h2 id="formats-heading">A little perspective.<br/>Good company.</h2></div><div className="expertise-grid"><article className="expertise-item"><span className="item-number">01</span><h3>Business<br/>workshops</h3><p>Bring a real business question. Work through the decisions, explore where AI can help, and leave with a clearer next step.</p></article><article className="expertise-item"><span className="item-number">02</span><h3>Founder<br/>gatherings</h3><p>Dinners and social experiences for people building businesses. Room for honest conversations, shared ideas, and enjoying the company.</p></article><article className="expertise-item"><span className="item-number">03</span><h3>Venue<br/>programming</h3><p>Experiences commissioned by cafés, bars, and organizations. Built around your audience, your space, and a reason for people to return.</p></article></div></section>
 <section className="events-venue" aria-labelledby="venue-heading"><div className="container events-venue-inner"><div><p className="eyebrow">For venues & organizations</p><h2 id="venue-heading">Give people<br/>a reason to come in.</h2></div><div><p>Tell us about your space, the people you want to reach, and the days that could use more life. We’ll discuss a program that makes sense for your business.</p><button className="button button-white" onClick={()=>contact("Venue programming")}>Discuss a program <ArrowUpRight size={19}/></button></div></div></section>
 </main>
 <footer className="site-footer"><div className="container footer-top"><Brand large/><div><span className="eyebrow">Business strategy & implementation</span><p>Detroit, Michigan</p></div><a href="/#expertise" className="back-top">Explore the firm <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Brown & Gaines</span><SocialLinks/><a href="/">Back to Brown & Gaines</a></div></footer>
 <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent className="mobile-sheet"><SheetTitle className="sheet-brand">Brown & Gaines</SheetTitle><SheetDescription>Business strategy & implementation</SheetDescription><nav aria-label="Mobile navigation">{links.map(([label,url])=><a key={url} href={url} onClick={()=>setMenuOpen(false)} aria-current={url==="/events"?"page":undefined}>{label}<ArrowUpRight size={19}/></a>)}</nav><button className="button button-blue" onClick={()=>contact("Not sure yet")}>Start a conversation <ArrowUpRight size={19}/></button></SheetContent></Sheet>
 <InquiryDialog key={requestId} open={contactOpen} onOpenChange={setContactOpen} initialInterest={interest} requestId={requestId} source="event"/>
 </>;
}
