"use client";
import {useState} from "react";
import {ArrowUpRight, ArrowRight, Menu} from "lucide-react";
import { SocialLinks } from "@/components/social-links";
import {Brand} from "@/components/site-brand";
import {InquiryDialog} from "@/components/inquiry-dialog";
import {Sheet, SheetContent, SheetTitle, SheetDescription} from "@/components/ui/sheet";
const links=[["Our expertise","/#expertise"],["In practice","/in-practice/crm"],["Events","/events"],["Our firm","/our-firm"]];
export default function EventsPage(){
 const [menuOpen,setMenuOpen]=useState(false);
 const [contactOpen,setContactOpen]=useState(false);
 const [interest,setInterest]=useState("Founder events");
 const [requestId,setRequestId]=useState("");
 function contact(topic="Founder events"){if(topic!=="Founder events"&&topic!=="Venue programming"){window.location.assign("/start?source=event");return;}setMenuOpen(false);setInterest(topic);setRequestId(crypto.randomUUID());setContactOpen(true)}
 return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/>
 <header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,url])=><a key={url} href={url} aria-current={url==="/events"?"page":undefined}>{label}</a>)}</nav><button className="header-contact" onClick={()=>contact("Not sure yet")}>Start a conversation <ArrowUpRight size={17}/></button><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><Menu size={25}/></button></div></header>
 <main id="main">
 <section className="events-hero" aria-labelledby="events-heading"><div className="container events-hero-grid"><div><a href="/" className="events-breadcrumb">Brown & Gaines <span>/</span> Ryan Brown & Company</a><p className="eyebrow">A Ryan Brown & Company experience</p><h1 id="events-heading">Good things<br/>happen in<br/><em>the right room.</em></h1><p className="events-intro">Curated gatherings, recurring formats, and venue programs designed to give people a reason to enter the room—and come back.</p><a href="#upcoming" className="text-link light-link">Explore upcoming events <ArrowRight size={19}/></a></div><figure className="events-image"><img src="/images/ryan-brown-company-events.jpg" width="1536" height="1024" alt="Guests arriving and connecting inside a restored Detroit event space" fetchPriority="high"/><span className="event-disco-rig" aria-hidden="true"><span className="event-disco-cord"/><span className="event-disco-cap"/><span className="event-disco-ball"/></span><figcaption className="photo-note">Arrival, energy, connection · Concept imagery</figcaption></figure></div></section>
 <section className="container events-calendar" id="upcoming" aria-labelledby="upcoming-heading"><div className="events-section-heading"><p className="eyebrow">On the calendar</p><h2 id="upcoming-heading">Upcoming events</h2></div><div className="event-list">
<article className="event-feature" id="inaugural-dinner"><div className="event-date"><span>SEP</span><strong>10</strong><span>2026</span></div><div><p className="eyebrow">The inaugural gathering · By invitation</p><h3>The Founders’ Dinner</h3><p className="event-description">Our first table. An evening for founders to share a meal, trade perspectives, and begin the conversations that carry beyond the room.</p><dl className="event-details"><div><dt>When</dt><dd>Thursday, September 10, 2026<br/>5:30–8:30 PM Eastern</dd></div><div><dt>Where</dt><dd>Spaces at Stix<br/>19646 W Nine Mile Road<br/>Southfield, MI 48075</dd></div></dl><p className="event-status">Private, invitation-only dinner. Invitations are managed directly by the hosts.</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Spaces+at+Stix+19646+W+Nine+Mile+Road+Southfield+MI+48075" target="_blank" rel="noopener noreferrer">View location <ArrowUpRight size={18}/></a></div></article>
<div className="event-coming-grid"><article id="match-made" className="event-coming"><p className="eyebrow">October 9, 2026 · Community programming</p><h3>Match Made</h3><p>A date night with a live speed-date show, hosted by Shima. Singles happy hour from 6–7 PM, the show from 7–8 PM, and mix & mingle from 8–9 PM.</p><p className="event-status">The Congregation · Detroit<br/>Friday, October 9 · 6–9 PM Eastern</p><a href="/images/match-made-flyer.png" className="event-flyer-link" target="_blank" rel="noopener noreferrer" aria-label="Open the Match Made flyer preview"><img className="event-flyer" src="/images/match-made-flyer.png" alt="Match Made Speed Dates, October 9, hosted by Shima at The Congregation Detroit, 6–9 PM. Curated by Ryan Brown & Co. Flyer preview includes a QR placeholder; registration is not yet open here." width="1024" height="1536" loading="lazy"/></a><p className="event-credit">A Ryan Brown & Company experience, from Brown & Gaines. Original flyer credits retained.</p><p className="event-status">Flyer preview · QR code pending. Eventbrite registration link coming soon.</p></article><article className="event-coming" id="uno"><p className="eyebrow">In development</p><h3>UNO, in good company.</h3><p>A game night for founders and friends. Bring your competitive streak and leave room for a new connection.</p><p className="event-status">The format, date, and venue are being finalized.</p><button className="text-link" onClick={()=>contact("Founder events")}>Ask about game night <ArrowUpRight size={18}/></button></article></div></div></section>
 <section className="container events-formats" aria-labelledby="formats-heading"><div className="events-section-heading"><p className="eyebrow">Ways we gather</p><h2 id="formats-heading">A little perspective.<br/>Good company.</h2></div><div className="expertise-grid"><article className="expertise-item"><span className="item-number">01</span><h3>Business<br/>workshops</h3><p>Bring a real business question. Work through the decisions, explore where AI can help, and leave with a clearer next step.</p></article><article className="expertise-item"><span className="item-number">02</span><h3>Founder<br/>gatherings</h3><p>Dinners and social experiences for people building businesses. Room for honest conversations, shared ideas, and enjoying the company.</p></article><article className="expertise-item"><span className="item-number">03</span><h3>Venue<br/>programming</h3><p>Experiences commissioned by cafés, bars, and organizations. Built around your audience, your space, and a reason for people to return.</p></article></div></section>
 <section className="events-venue" aria-labelledby="venue-heading"><div className="container events-venue-inner"><div><p className="eyebrow">For venues & organizations</p><h2 id="venue-heading">Give people<br/>a reason to come in.</h2></div><div><p>Tell us about your space, the people you want to reach, and the days that could use more life. We’ll discuss a program that makes sense for your business.</p><button className="button button-white" onClick={()=>contact("Venue programming")}>Discuss a program <ArrowUpRight size={19}/></button></div></div></section>
 </main>
 <footer className="site-footer"><div className="container footer-top"><Brand large/><div><span className="eyebrow">Business strategy & implementation</span><p>Detroit, Michigan</p></div><a href="/#expertise" className="back-top">Explore the firm <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Brown & Gaines</span><SocialLinks/><a href="/">Back to Brown & Gaines</a></div></footer>
 <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent className="mobile-sheet"><SheetTitle className="sheet-brand">Brown & Gaines</SheetTitle><SheetDescription>Business strategy & implementation</SheetDescription><nav aria-label="Mobile navigation">{links.map(([label,url])=><a key={url} href={url} onClick={()=>setMenuOpen(false)} aria-current={url==="/events"?"page":undefined}>{label}<ArrowUpRight size={19}/></a>)}</nav><button className="button button-blue" onClick={()=>contact("Not sure yet")}>Start a conversation <ArrowUpRight size={19}/></button></SheetContent></Sheet>
 <InquiryDialog key={requestId} open={contactOpen} onOpenChange={setContactOpen} initialInterest={interest} requestId={requestId} source="event"/>
 </>;
}
